# -*- coding: utf-8 -*-
"""
tasteofhome.tags
"""

"""
	DECLARE csrProvince CURSOR FOR SELECT ProID, ProName FROM T_Province ORDER BY ProSort
	OPEN csrProvince
	DECLARE @pid INT, @province NVARCHAR(128)
	DECLARE @depth INT
	FETCH NEXT FROM csrProvince INTO @pid, @province
	WHILE (@@FETCH_STATUS <> -1)
	BEGIN
		SET @depth=1
		PRINT 'tag=Tag(name=u'''+@province+''', depth='+CONVERT(NVARCHAR, @depth)+')'
		PRINT 'key=tag.put()'
		DECLARE csrCity CURSOR FOR SELECT CityID, CityName FROM T_City WHERE ProID=@pid ORDER BY CitySort
		OPEN csrCity
		DECLARE @cid INT, @city NVARCHAR(128)
		FETCH NEXT FROM csrCity INTO @cid, @city
		WHILE (@@FETCH_STATUS<>-1)
		BEGIN
			SET @depth=1
			IF (@city<>@province)
			BEGIN
				SET @depth=@depth+1
				PRINT 'tag=Tag(name=u'''+@city+''', parent=key, depth='+CONVERT(NVARCHAR, @depth)+')'
				PRINT 'key=tag.put()'
			END
			SET @depth=@depth+1
			DECLARE @districts NVARCHAR(2048)
			SELECT @districts=NULL
			SELECT @districts=COALESCE(@districts+', ','')+'u'''+DisName+'''' FROM T_District WHERE CityID=@cid ORDER BY DisSort
			IF (@districts IS NOT NULL) PRINT 'db.put([Tag(parent=key, name=t, depth='+CONVERT(NVARCHAR, @depth)+') for t in [' + @districts +']])'
			PRINT 'key=key.parent()'
			FETCH NEXT FROM csrCity INTO @cid, @city
		END
		CLOSE csrCity
		DEALLOCATE csrCity
		FETCH NEXT FROM csrProvince INTO @pid, @province
	END
	CLOSE csrProvince
	DEALLOCATE csrProvince
"""

from kay.utils import render_to_response
from models import Tag
from google.appengine.ext import db
from google.appengine.ext import deferred

def tags(request):
    deferred.defer(populate_tags)
    return  render_to_response('tasteofhome/index.html', {'message': 'deferred tags population'})

def populate_tags():
    tag=Tag(name=u'北京市', depth=1)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=2) for t in [u'东城区', u'西城区', u'崇文区', u'宣武区', u'朝阳区', u'丰台区', u'石景山区', u'海淀区', u'门头沟区', u'房山区', u'通州区', u'顺义区', u'昌平区', u'大兴区', u'怀柔区', u'平谷区', u'密云县', u'延庆县']])
    key=key.parent()
    tag=Tag(name=u'天津市', depth=1)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=2) for t in [u'和平区', u'河东区', u'河西区', u'南开区', u'河北区', u'红桥区', u'塘沽区', u'汉沽区', u'大港区', u'东丽区', u'西青区', u'津南区', u'北辰区', u'武清区', u'宝坻区', u'宁河县', u'静海县', u'蓟县']])
    key=key.parent()
    tag=Tag(name=u'上海市', depth=1)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=2) for t in [u'黄浦区', u'卢湾区', u'徐汇区', u'长宁区', u'静安区', u'普陀区', u'闸北区', u'虹口区', u'杨浦区', u'闵行区', u'宝山区', u'嘉定区', u'浦东新区', u'金山区', u'松江区', u'青浦区', u'南汇区', u'奉贤区', u'崇明县']])
    key=key.parent()
    tag=Tag(name=u'重庆市', depth=1)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=2) for t in [u'万州区', u'涪陵区', u'渝中区', u'大渡口区', u'江北区', u'沙坪坝区', u'九龙坡区', u'南岸区', u'北碚区', u'万盛区', u'双桥区', u'渝北区', u'巴南区', u'黔江区', u'长寿区', u'江津区', u'合川区', u'永川区', u'南川区', u'綦江县', u'潼南县', u'铜梁县', u'大足县', u'荣昌县', u'璧山县', u'梁平县', u'城口县', u'丰都县', u'垫江县', u'武隆县', u'忠县', u'开县', u'云阳县', u'奉节县', u'巫山县', u'巫溪县', u'石柱土家族自治县', u'秀山土家族苗族自治县', u'酉阳土家族苗族自治县', u'彭水苗族土家族自治县']])
    key=key.parent()
    tag=Tag(name=u'河北省', depth=1)
    key=tag.put()
    tag=Tag(name=u'邯郸市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'邯山区', u'丛台区', u'复兴区', u'峰峰矿区', u'邯郸县', u'临漳县', u'成安县', u'大名县', u'涉县', u'磁县', u'肥乡县', u'永年县', u'邱县', u'鸡泽县', u'广平县', u'馆陶县', u'魏县', u'曲周县', u'武安市']])
    key=key.parent()
    tag=Tag(name=u'石家庄市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'长安区', u'桥东区', u'桥西区', u'新华区', u'井陉矿区', u'裕华区', u'井陉县', u'正定县', u'栾城县', u'行唐县', u'灵寿县', u'高邑县', u'深泽县', u'赞皇县', u'无极县', u'平山县', u'元氏县', u'赵县', u'辛集市', u'藁城市', u'晋州市', u'新乐市', u'鹿泉市']])
    key=key.parent()
    tag=Tag(name=u'保定市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'新市区', u'北市区', u'南市区', u'满城县', u'清苑县', u'涞水县', u'阜平县', u'徐水县', u'定兴县', u'唐县', u'高阳县', u'容城县', u'涞源县', u'望都县', u'安新县', u'易县', u'曲阳县', u'蠡县', u'顺平县', u'博野县', u'雄县', u'涿州市', u'定州市', u'安国市', u'高碑店市']])
    key=key.parent()
    tag=Tag(name=u'张家口市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'桥东区', u'桥西区', u'宣化区', u'下花园区', u'宣化县', u'张北县', u'康保县', u'沽源县', u'尚义县', u'蔚县', u'阳原县', u'怀安县', u'万全县', u'怀来县', u'涿鹿县', u'赤城县', u'崇礼县']])
    key=key.parent()
    tag=Tag(name=u'承德市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'双桥区', u'双滦区', u'鹰手营子矿区', u'承德县', u'兴隆县', u'平泉县', u'滦平县', u'隆化县', u'丰宁满族自治县', u'宽城满族自治县', u'围场满族蒙古族自治县']])
    key=key.parent()
    tag=Tag(name=u'唐山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'路南区', u'路北区', u'古冶区', u'开平区', u'丰南区', u'丰润区', u'滦县', u'滦南县', u'乐亭县', u'迁西县', u'玉田县', u'唐海县', u'遵化市', u'迁安市']])
    key=key.parent()
    tag=Tag(name=u'廊坊市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'安次区', u'广阳区', u'固安县', u'永清县', u'香河县', u'大城县', u'文安县', u'大厂回族自治县', u'霸州市', u'三河市']])
    key=key.parent()
    tag=Tag(name=u'沧州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'新华区', u'运河区', u'沧县', u'青县', u'东光县', u'海兴县', u'盐山县', u'肃宁县', u'南皮县', u'吴桥县', u'献县', u'孟村回族自治县', u'泊头市', u'任丘市', u'黄骅市', u'河间市']])
    key=key.parent()
    tag=Tag(name=u'衡水市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'桃城区', u'枣强县', u'武邑县', u'武强县', u'饶阳县', u'安平县', u'故城县', u'景县', u'阜城县', u'冀州市', u'深州市']])
    key=key.parent()
    tag=Tag(name=u'邢台市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'桥东区', u'桥西区', u'邢台县', u'临城县', u'内丘县', u'柏乡县', u'隆尧县', u'任县', u'南和县', u'宁晋县', u'巨鹿县', u'新河县', u'广宗县', u'平乡县', u'威县', u'清河县', u'临西县', u'南宫市', u'沙河市']])
    key=key.parent()
    tag=Tag(name=u'秦皇岛市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'海港区', u'山海关区', u'北戴河区', u'青龙满族自治县', u'昌黎县', u'抚宁县', u'卢龙县']])
    key=key.parent()
    tag=Tag(name=u'山西省', depth=1)
    key=tag.put()
    tag=Tag(name=u'朔州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'朔城区', u'平鲁区', u'山阴县', u'应县', u'右玉县', u'怀仁县']])
    key=key.parent()
    tag=Tag(name=u'忻州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'忻府区', u'定襄县', u'五台县', u'代县', u'繁峙县', u'宁武县', u'静乐县', u'神池县', u'五寨县', u'岢岚县', u'河曲县', u'保德县', u'偏关县', u'原平市']])
    key=key.parent()
    tag=Tag(name=u'太原市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'小店区', u'迎泽区', u'杏花岭区', u'尖草坪区', u'万柏林区', u'晋源区', u'清徐县', u'阳曲县', u'娄烦县', u'古交市']])
    key=key.parent()
    tag=Tag(name=u'大同市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'矿区', u'南郊区', u'新荣区', u'阳高县', u'天镇县', u'广灵县', u'灵丘县', u'浑源县', u'左云县', u'大同县']])
    key=key.parent()
    tag=Tag(name=u'阳泉市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'矿区', u'平定县', u'盂县']])
    key=key.parent()
    tag=Tag(name=u'晋中市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'榆次区', u'榆社县', u'左权县', u'和顺县', u'昔阳县', u'寿阳县', u'太谷县', u'祁县', u'平遥县', u'灵石县', u'介休市']])
    key=key.parent()
    tag=Tag(name=u'长治市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'长治县', u'襄垣县', u'屯留县', u'平顺县', u'黎城县', u'壶关县', u'长子县', u'武乡县', u'沁县', u'沁源县', u'潞城市']])
    key=key.parent()
    tag=Tag(name=u'晋城市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'沁水县', u'阳城县', u'陵川县', u'泽州县', u'高平市']])
    key=key.parent()
    tag=Tag(name=u'临汾市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'尧都区', u'曲沃县', u'翼城县', u'襄汾县', u'洪洞县', u'古县', u'安泽县', u'浮山县', u'吉县', u'乡宁县', u'大宁县', u'隰县', u'永和县', u'蒲县', u'汾西县', u'侯马市', u'霍州市']])
    key=key.parent()
    tag=Tag(name=u'吕梁市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'离石区', u'文水县', u'交城县', u'兴县', u'临县', u'柳林县', u'石楼县', u'岚县', u'方山县', u'中阳县', u'交口县', u'孝义市', u'汾阳市']])
    key=key.parent()
    tag=Tag(name=u'运城市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'盐湖区', u'临猗县', u'万荣县', u'闻喜县', u'稷山县', u'新绛县', u'绛县', u'垣曲县', u'夏县', u'平陆县', u'芮城县', u'永济市', u'河津市']])
    key=key.parent()
    tag=Tag(name=u'台湾省', depth=1)
    key=tag.put()
    tag=Tag(name=u'台北市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'高雄市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'基隆市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'台中市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'台南市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'新竹市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'嘉义市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'辽宁省', depth=1)
    key=tag.put()
    tag=Tag(name=u'沈阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'和平区', u'沈河区', u'大东区', u'皇姑区', u'铁西区', u'苏家屯区', u'东陵区', u'沈北新区', u'于洪区', u'辽中县', u'康平县', u'法库县', u'新民市']])
    key=key.parent()
    tag=Tag(name=u'铁岭市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'银州区', u'清河区', u'铁岭县', u'西丰县', u'昌图县', u'调兵山市', u'开原市']])
    key=key.parent()
    tag=Tag(name=u'大连市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'长海县', u'旅顺口区', u'中山区', u'西岗区', u'沙河口区', u'甘井子区', u'金州区', u'普兰店市', u'瓦房店市', u'庄河市']])
    key=key.parent()
    tag=Tag(name=u'鞍山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'铁东区', u'铁西区', u'立山区', u'千山区', u'台安县', u'岫岩满族自治县', u'海城市']])
    key=key.parent()
    tag=Tag(name=u'抚顺市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'新抚区', u'东洲区', u'望花区', u'顺城区', u'抚顺县', u'新宾满族自治县', u'清原满族自治县']])
    key=key.parent()
    tag=Tag(name=u'本溪市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'平山区', u'溪湖区', u'明山区', u'南芬区', u'本溪满族自治县', u'桓仁满族自治县']])
    key=key.parent()
    tag=Tag(name=u'丹东市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'元宝区', u'振兴区', u'振安区', u'宽甸满族自治县', u'东港市', u'凤城市']])
    key=key.parent()
    tag=Tag(name=u'锦州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'古塔区', u'凌河区', u'太和区', u'黑山县', u'义县', u'凌海市', u'北镇市']])
    key=key.parent()
    tag=Tag(name=u'营口市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'站前区', u'西市区', u'鮁鱼圈区', u'老边区', u'盖州市', u'大石桥市']])
    key=key.parent()
    tag=Tag(name=u'阜新市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'海州区', u'新邱区', u'太平区', u'清河门区', u'细河区', u'阜新蒙古族自治县', u'彰武县']])
    key=key.parent()
    tag=Tag(name=u'辽阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'白塔区', u'文圣区', u'宏伟区', u'弓长岭区', u'太子河区', u'辽阳县', u'灯塔市']])
    key=key.parent()
    tag=Tag(name=u'朝阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'双塔区', u'龙城区', u'朝阳县', u'建平县', u'喀喇沁左翼蒙古族自治县', u'北票市', u'凌源市']])
    key=key.parent()
    tag=Tag(name=u'盘锦市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'双台子区', u'兴隆台区', u'大洼县', u'盘山县']])
    key=key.parent()
    tag=Tag(name=u'葫芦岛市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'连山区', u'龙港区', u'南票区', u'绥中县', u'建昌县', u'兴城市']])
    key=key.parent()
    tag=Tag(name=u'吉林省', depth=1)
    key=tag.put()
    tag=Tag(name=u'长春市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'南关区', u'宽城区', u'朝阳区', u'二道区', u'绿园区', u'双阳区', u'农安县', u'九台市', u'榆树市', u'德惠市']])
    key=key.parent()
    tag=Tag(name=u'吉林市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'昌邑区', u'龙潭区', u'船营区', u'丰满区', u'永吉县', u'蛟河市', u'桦甸市', u'舒兰市', u'磐石市']])
    key=key.parent()
    tag=Tag(name=u'延边朝鲜族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'延吉市', u'图们市', u'敦化市', u'珲春市', u'龙井市', u'和龙市', u'汪清县', u'安图县']])
    key=key.parent()
    tag=Tag(name=u'四平市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'铁西区', u'铁东区', u'梨树县', u'伊通满族自治县', u'公主岭市', u'双辽市']])
    key=key.parent()
    tag=Tag(name=u'通化市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'东昌区', u'二道江区', u'通化县', u'辉南县', u'柳河县', u'梅河口市', u'集安市']])
    key=key.parent()
    tag=Tag(name=u'白城市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'洮北区', u'镇赉县', u'通榆县', u'洮南市', u'大安市']])
    key=key.parent()
    tag=Tag(name=u'辽源市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'龙山区', u'西安区', u'东丰县', u'东辽县']])
    key=key.parent()
    tag=Tag(name=u'松原市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'宁江区', u'前郭尔罗斯蒙古族自治县', u'长岭县', u'乾安县', u'扶余县']])
    key=key.parent()
    tag=Tag(name=u'白山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'八道江区', u'江源区', u'抚松县', u'靖宇县', u'长白朝鲜族自治县', u'临江市']])
    key=key.parent()
    tag=Tag(name=u'黑龙江省', depth=1)
    key=tag.put()
    tag=Tag(name=u'哈尔滨市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'道里区', u'南岗区', u'道外区', u'平房区', u'松北区', u'香坊区', u'呼兰区', u'阿城区', u'依兰县', u'方正县', u'宾县', u'巴彦县', u'木兰县', u'通河县', u'延寿县', u'双城市', u'尚志市', u'五常市']])
    key=key.parent()
    tag=Tag(name=u'齐齐哈尔市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'龙沙区', u'建华区', u'铁锋区', u'昂昂溪区', u'富拉尔基区', u'碾子山区', u'梅里斯达翰尔族区', u'龙江县', u'依安县', u'泰来县', u'甘南县', u'富裕县', u'克山县', u'克东县', u'拜泉县', u'讷河市']])
    key=key.parent()
    tag=Tag(name=u'鸡西市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'鸡冠区', u'恒山区', u'滴道区', u'梨树区', u'城子河区', u'麻山区', u'鸡东县', u'虎林市', u'密山市']])
    key=key.parent()
    tag=Tag(name=u'牡丹江市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'东安区', u'阳明区', u'爱民区', u'西安区', u'东宁县', u'林口县', u'绥芬河市', u'海林市', u'宁安市', u'穆棱市']])
    key=key.parent()
    tag=Tag(name=u'七台河市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'新兴区', u'桃山区', u'茄子河区', u'勃利县']])
    key=key.parent()
    tag=Tag(name=u'佳木斯市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'向阳区', u'前进区', u'东风区', u'桦南县', u'桦川县', u'汤原县', u'抚远县', u'同江市', u'富锦市']])
    key=key.parent()
    tag=Tag(name=u'鹤岗市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'向阳区', u'工农区', u'南山区', u'兴安区', u'东山区', u'兴山区', u'萝北县', u'绥滨县']])
    key=key.parent()
    tag=Tag(name=u'双鸭山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'尖山区', u'岭东区', u'四方台区', u'宝山区', u'集贤县', u'友谊县', u'宝清县', u'饶河县']])
    key=key.parent()
    tag=Tag(name=u'绥化市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'北林区', u'望奎县', u'兰西县', u'青冈县', u'庆安县', u'明水县', u'绥棱县', u'安达市', u'肇东市', u'海伦市']])
    key=key.parent()
    tag=Tag(name=u'黑河市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'爱辉区', u'嫩江县', u'逊克县', u'孙吴县', u'北安市', u'五大连池市']])
    key=key.parent()
    tag=Tag(name=u'大兴安岭地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'呼玛县', u'塔河县', u'漠河县']])
    key=key.parent()
    tag=Tag(name=u'伊春市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'伊春区', u'南岔区', u'友好区', u'西林区', u'翠峦区', u'新青区', u'美溪区', u'金山屯区', u'五营区', u'乌马河区', u'汤旺河区', u'带岭区', u'乌伊岭区', u'红星区', u'上甘岭区', u'嘉荫县', u'铁力市']])
    key=key.parent()
    tag=Tag(name=u'大庆市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'萨尔图区', u'龙凤区', u'让胡路区', u'红岗区', u'大同区', u'肇州县', u'肇源县', u'林甸县', u'杜尔伯特蒙古族自治县']])
    key=key.parent()
    tag=Tag(name=u'江苏省', depth=1)
    key=tag.put()
    tag=Tag(name=u'南京市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'江宁区', u'浦口区', u'玄武区', u'白下区', u'秦淮区', u'建邺区', u'鼓楼区', u'下关区', u'栖霞区', u'雨花台区', u'六合区', u'溧水县', u'高淳县']])
    key=key.parent()
    tag=Tag(name=u'无锡市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'崇安区', u'南长区', u'北塘区', u'锡山区', u'惠山区', u'滨湖区', u'江阴市', u'宜兴市']])
    key=key.parent()
    tag=Tag(name=u'镇江市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'京口区', u'润州区', u'丹徒区', u'丹阳市', u'扬中市', u'句容市']])
    key=key.parent()
    tag=Tag(name=u'苏州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'沧浪区', u'常熟市', u'平江区', u'金阊区', u'虎丘区', u'昆山市', u'太仓市', u'吴江市', u'吴中区', u'相城区', u'张家港市']])
    key=key.parent()
    tag=Tag(name=u'南通市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'崇川区', u'港闸区', u'海安县', u'如东县', u'启东市', u'如皋市', u'通州市', u'海门市']])
    key=key.parent()
    tag=Tag(name=u'扬州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'高邮市', u'广陵区', u'邗江区', u'维扬区', u'宝应县', u'江都市', u'仪征市']])
    key=key.parent()
    tag=Tag(name=u'盐城市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'亭湖区', u'盐都区', u'响水县', u'滨海县', u'阜宁县', u'射阳县', u'建湖县', u'东台市', u'大丰市']])
    key=key.parent()
    tag=Tag(name=u'徐州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'鼓楼区', u'云龙区', u'九里区', u'贾汪区', u'泉山区', u'丰县', u'沛县', u'铜山县', u'睢宁县', u'新沂市', u'邳州市']])
    key=key.parent()
    tag=Tag(name=u'淮安市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'清河区', u'楚州区', u'淮阴区', u'清浦区', u'涟水县', u'洪泽县', u'盱眙县', u'金湖县']])
    key=key.parent()
    tag=Tag(name=u'连云港市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'连云区', u'新浦区', u'海州区', u'赣榆县', u'东海县', u'灌云县', u'灌南县']])
    key=key.parent()
    tag=Tag(name=u'常州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'天宁区', u'钟楼区', u'戚墅堰区', u'新北区', u'武进区', u'溧阳市', u'金坛市']])
    key=key.parent()
    tag=Tag(name=u'泰州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'海陵区', u'高港区', u'兴化市', u'靖江市', u'泰兴市', u'姜堰市']])
    key=key.parent()
    tag=Tag(name=u'宿迁市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'宿城区', u'宿豫区', u'沭阳县', u'泗阳县', u'泗洪县']])
    key=key.parent()
    tag=Tag(name=u'浙江省', depth=1)
    key=tag.put()
    tag=Tag(name=u'舟山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'定海区', u'普陀区', u'岱山县', u'嵊泗县']])
    key=key.parent()
    tag=Tag(name=u'衢州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'柯城区', u'衢江区', u'常山县', u'开化县', u'龙游县', u'江山市']])
    key=key.parent()
    tag=Tag(name=u'杭州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'上城区', u'下城区', u'江干区', u'拱墅区', u'西湖区', u'滨江区', u'余杭区', u'桐庐县', u'淳安县', u'建德市', u'富阳市', u'临安市', u'萧山区']])
    key=key.parent()
    tag=Tag(name=u'湖州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'吴兴区', u'南浔区', u'德清县', u'长兴县', u'安吉县']])
    key=key.parent()
    tag=Tag(name=u'嘉兴市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u' 南湖区', u' 秀洲区', u' 嘉善县', u' 海盐县', u' 海宁市', u' 平湖市', u' 桐乡市 ']])
    key=key.parent()
    tag=Tag(name=u'宁波市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'海曙区', u'江东区', u'江北区', u'北仑区', u'镇海区', u'鄞州区', u'象山县', u'宁海县', u'余姚市', u'慈溪市', u'奉化市']])
    key=key.parent()
    tag=Tag(name=u'绍兴市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'越城区', u'绍兴县', u'新昌县', u'诸暨市', u'上虞市', u'嵊州市']])
    key=key.parent()
    tag=Tag(name=u'温州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'鹿城区', u'龙湾区', u'瓯海区', u'洞头县', u'永嘉县', u'平阳县', u'苍南县', u'文成县', u'泰顺县', u'瑞安市', u'乐清市']])
    key=key.parent()
    tag=Tag(name=u'丽水市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'莲都区', u'青田县', u'缙云县', u'遂昌县', u'松阳县', u'云和县', u'庆元县', u'景宁畲族自治县', u'龙泉市']])
    key=key.parent()
    tag=Tag(name=u'金华市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'婺城区', u'金东区', u'武义县', u'浦江县', u'磐安县', u'兰溪市', u'义乌市', u'东阳市', u'永康市']])
    key=key.parent()
    tag=Tag(name=u'台州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'椒江区', u'黄岩区', u'路桥区', u'玉环县', u'三门县', u'天台县', u'仙居县', u'温岭市', u'临海市']])
    key=key.parent()
    tag=Tag(name=u'安徽省', depth=1)
    key=tag.put()
    tag=Tag(name=u'合肥市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'瑶海区', u'庐阳区', u'蜀山区', u'包河区', u'长丰县', u'肥东县', u'肥西县']])
    key=key.parent()
    tag=Tag(name=u'芜湖市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'镜湖区', u'弋江区', u'鸠江区', u'三山区', u'芜湖县', u'繁昌县', u'南陵县']])
    key=key.parent()
    tag=Tag(name=u'蚌埠市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'龙子湖区', u'蚌山区', u'禹会区', u'淮上区', u'怀远县', u'五河县', u'固镇县']])
    key=key.parent()
    tag=Tag(name=u'淮南市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'大通区', u'田家庵区', u'谢家集区', u'八公山区', u'潘集区', u'凤台县']])
    key=key.parent()
    tag=Tag(name=u'马鞍山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'金家庄区', u'花山区', u'雨山区', u'当涂县']])
    key=key.parent()
    tag=Tag(name=u'淮北市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'杜集区', u'相山区', u'烈山区', u'濉溪县 ']])
    key=key.parent()
    tag=Tag(name=u'铜陵市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'铜官山区', u'狮子山区', u'铜陵县']])
    key=key.parent()
    tag=Tag(name=u'安庆市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'迎江区', u'大观区', u'宜秀区', u'怀宁县', u'枞阳县', u'潜山县', u'太湖县', u'宿松县', u'望江县', u'岳西县', u'桐城市']])
    key=key.parent()
    tag=Tag(name=u'黄山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'屯溪区', u'黄山区', u'徽州区', u'歙县', u'休宁县', u'黟县', u'祁门县']])
    key=key.parent()
    tag=Tag(name=u'滁州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'琅琊区', u'南谯区', u'来安县', u'全椒县', u'定远县', u'凤阳县', u'天长市', u'明光市']])
    key=key.parent()
    tag=Tag(name=u'阜阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'颍州区', u'颍东区', u'颍泉区', u'临泉县', u'太和县', u'阜南县', u'颍上县', u'界首市']])
    key=key.parent()
    tag=Tag(name=u'宿州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'埇桥区', u'砀山县', u'萧县', u'灵璧县', u'泗县 ']])
    key=key.parent()
    tag=Tag(name=u'巢湖市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'居巢区', u'庐江县', u'无为县', u'含山县', u'和县 ']])
    key=key.parent()
    tag=Tag(name=u'六安市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'金安区', u'裕安区', u'寿县', u'霍邱县', u'舒城县', u'金寨县', u'霍山县']])
    key=key.parent()
    tag=Tag(name=u'亳州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'谯城区', u'涡阳县', u'蒙城县', u'利辛县']])
    key=key.parent()
    tag=Tag(name=u'池州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'贵池区', u'东至县', u'石台县', u'青阳县']])
    key=key.parent()
    tag=Tag(name=u'宣城市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'宣州区', u'郎溪县', u'广德县', u'泾县', u'绩溪县', u'旌德县', u'宁国市']])
    key=key.parent()
    tag=Tag(name=u'福建省', depth=1)
    key=tag.put()
    tag=Tag(name=u'福州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'鼓楼区', u'台江区', u'仓山区', u'马尾区', u'晋安区', u'闽侯县', u'连江县', u'罗源县', u'闽清县', u'永泰县', u'平潭县', u'福清市', u'长乐市']])
    key=key.parent()
    tag=Tag(name=u'厦门市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'思明区', u'海沧区', u'湖里区', u'集美区', u'同安区', u'翔安区']])
    key=key.parent()
    tag=Tag(name=u'宁德市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'蕉城区', u'霞浦县', u'古田县', u'屏南县', u'寿宁县', u'周宁县', u'柘荣县', u'福安市', u'福鼎市']])
    key=key.parent()
    tag=Tag(name=u'莆田市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'城厢区', u'涵江区', u'荔城区', u'秀屿区', u'仙游县']])
    key=key.parent()
    tag=Tag(name=u'泉州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'鲤城区', u'丰泽区', u'洛江区', u'泉港区', u'惠安县', u'安溪县', u'永春县', u'德化县', u'石狮市', u'晋江市', u'南安市']])
    key=key.parent()
    tag=Tag(name=u'漳州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'芗城区', u'龙文区', u'云霄县', u'漳浦县', u'诏安县', u'长泰县', u'东山县', u'南靖县', u'平和县', u'华安县', u'龙海市']])
    key=key.parent()
    tag=Tag(name=u'龙岩市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'新罗区', u'长汀县', u'永定县', u'上杭县', u'武平县', u'连城县', u'漳平市']])
    key=key.parent()
    tag=Tag(name=u'三明市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'梅列区', u'三元区', u'明溪县', u'清流县', u'宁化县', u'大田县', u'尤溪县', u'沙县', u'将乐县', u'泰宁县', u'建宁县', u'永安市']])
    key=key.parent()
    tag=Tag(name=u'南平市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'延平区', u'顺昌县', u'浦城县', u'光泽县', u'松溪县', u'政和县', u'邵武市', u'武夷山市', u'建瓯市', u'建阳市']])
    key=key.parent()
    tag=Tag(name=u'江西省', depth=1)
    key=tag.put()
    tag=Tag(name=u'鹰潭市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'月湖区', u'余江县', u'贵溪市']])
    key=key.parent()
    tag=Tag(name=u'新余市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'渝水区', u'分宜县']])
    key=key.parent()
    tag=Tag(name=u'南昌市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'东湖区', u'西湖区', u'青云谱区', u'湾里区', u'青山湖区', u'南昌县', u'新建县', u'安义县', u'进贤县']])
    key=key.parent()
    tag=Tag(name=u'九江市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'庐山区', u'浔阳区', u'九江县', u'武宁县', u'修水县', u'永修县', u'德安县', u'星子县', u'都昌县', u'湖口县', u'彭泽县', u'瑞昌市']])
    key=key.parent()
    tag=Tag(name=u'上饶市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'信州区', u'上饶县', u'广丰县', u'玉山县', u'铅山县', u'横峰县', u'弋阳县', u'余干县', u'鄱阳县', u'万年县', u'婺源县', u'德兴市']])
    key=key.parent()
    tag=Tag(name=u'抚州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'临川区', u'南城县', u'黎川县', u'南丰县', u'崇仁县', u'乐安县', u'宜黄县', u'金溪县', u'资溪县', u'东乡县', u'广昌县']])
    key=key.parent()
    tag=Tag(name=u'宜春市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'袁州区', u'奉新县', u'万载县', u'上高县', u'宜丰县', u'靖安县', u'铜鼓县', u'丰城市', u'樟树市', u'高安市']])
    key=key.parent()
    tag=Tag(name=u'吉安市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'吉州区', u'青原区', u'吉安县', u'吉水县', u'峡江县', u'新干县', u'永丰县', u'泰和县', u'遂川县', u'万安县', u'安福县', u'永新县', u'井冈山市']])
    key=key.parent()
    tag=Tag(name=u'赣州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'章贡区', u'赣县', u'信丰县', u'大余县', u'上犹县', u'崇义县', u'安远县', u'龙南县', u'定南县', u'全南县', u'宁都县', u'于都县', u'兴国县', u'会昌县', u'寻乌县', u'石城县', u'瑞金市', u'南康市']])
    key=key.parent()
    tag=Tag(name=u'景德镇市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'昌江区', u'珠山区', u'浮梁县', u'乐平市']])
    key=key.parent()
    tag=Tag(name=u'萍乡市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'安源区', u'湘东区', u'莲花县', u'上栗县', u'芦溪县']])
    key=key.parent()
    tag=Tag(name=u'山东省', depth=1)
    key=tag.put()
    tag=Tag(name=u'菏泽市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'牡丹区', u'曹县', u'单县', u'成武县', u'巨野县', u'郓城县', u'鄄城县', u'定陶县', u'东明县']])
    key=key.parent()
    tag=Tag(name=u'济南市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'历下区', u'市中区', u'槐荫区', u'天桥区', u'历城区', u'长清区', u'平阴县', u'济阳县', u'商河县', u'章丘市']])
    key=key.parent()
    tag=Tag(name=u'青岛市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'市南区', u'市北区', u'四方区', u'黄岛区', u'崂山区', u'李沧区', u'城阳区', u'胶州市', u'即墨市', u'平度市', u'胶南市', u'莱西市']])
    key=key.parent()
    tag=Tag(name=u'淄博市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'淄川区', u'张店区', u'博山区', u'临淄区', u'周村区', u'桓台县', u'高青县', u'沂源县']])
    key=key.parent()
    tag=Tag(name=u'德州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'德城区', u'陵县', u'宁津县', u'庆云县', u'临邑县', u'齐河县', u'平原县', u'夏津县', u'武城县', u'乐陵市', u'禹城市']])
    key=key.parent()
    tag=Tag(name=u'烟台市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'芝罘区', u'福山区', u'牟平区', u'莱山区', u'长岛县', u'龙口市', u'莱阳市', u'莱州市', u'蓬莱市', u'招远市', u'栖霞市', u'海阳市']])
    key=key.parent()
    tag=Tag(name=u'潍坊市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'潍城区', u'寒亭区', u'坊子区', u'奎文区', u'临朐县', u'昌乐县', u'青州市', u'诸城市', u'寿光市', u'安丘市', u'高密市', u'昌邑市']])
    key=key.parent()
    tag=Tag(name=u'济宁市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'市中区', u'任城区', u'微山县', u'鱼台县', u'金乡县', u'嘉祥县', u'汶上县', u'泗水县', u'梁山县', u'曲阜市', u'兖州市', u'邹城市']])
    key=key.parent()
    tag=Tag(name=u'泰安市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'泰山区', u'岱岳区', u'宁阳县', u'东平县', u'新泰市', u'肥城市']])
    key=key.parent()
    tag=Tag(name=u'临沂市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'兰山区', u'罗庄区', u'河东区', u'沂南县', u'郯城县', u'沂水县', u'苍山县', u'费县', u'平邑县', u'莒南县', u'蒙阴县', u'临沭县']])
    key=key.parent()
    tag=Tag(name=u'滨州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'滨城区', u'惠民县', u'阳信县', u'无棣县', u'沾化县', u'博兴县', u'邹平县']])
    key=key.parent()
    tag=Tag(name=u'东营市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'东营区', u'河口区', u'垦利县', u'利津县', u'广饶县']])
    key=key.parent()
    tag=Tag(name=u'威海市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'环翠区', u'文登市', u'荣成市', u'乳山市']])
    key=key.parent()
    tag=Tag(name=u'枣庄市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'市中区', u'薛城区', u'峄城区', u'台儿庄区', u'山亭区', u'滕州市']])
    key=key.parent()
    tag=Tag(name=u'日照市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'东港区', u'岚山区', u'五莲县', u'莒县']])
    key=key.parent()
    tag=Tag(name=u'莱芜市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'莱城区', u'钢城区']])
    key=key.parent()
    tag=Tag(name=u'聊城市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'东昌府区', u'阳谷县', u'莘县', u'茌平县', u'东阿县', u'冠县', u'高唐县', u'临清市']])
    key=key.parent()
    tag=Tag(name=u'河南省', depth=1)
    key=tag.put()
    tag=Tag(name=u'商丘市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'梁园区', u'睢阳区', u'民权县', u'睢县', u'宁陵县', u'柘城县', u'虞城县', u'夏邑县', u'永城市']])
    key=key.parent()
    tag=Tag(name=u'郑州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'中原区', u'二七区', u'管城回族区', u'金水区', u'上街区', u'惠济区', u'中牟县', u'巩义市', u'荥阳市', u'新密市', u'新郑市', u'登封市']])
    key=key.parent()
    tag=Tag(name=u'安阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'文峰区', u'北关区', u'殷都区', u'龙安区', u'安阳县', u'汤阴县', u'滑县', u'内黄县', u'林州市']])
    key=key.parent()
    tag=Tag(name=u'新乡市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'红旗区', u'卫滨区', u'凤泉区', u'牧野区', u'新乡县', u'获嘉县', u'原阳县', u'延津县', u'封丘县', u'长垣县', u'卫辉市', u'辉县市']])
    key=key.parent()
    tag=Tag(name=u'许昌市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'魏都区', u'许昌县', u'鄢陵县', u'襄城县', u'禹州市', u'长葛市']])
    key=key.parent()
    tag=Tag(name=u'平顶山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'新华区', u'卫东区', u'石龙区', u'湛河区', u'宝丰县', u'叶县', u'鲁山县', u'郏县', u'舞钢市', u'汝州市']])
    key=key.parent()
    tag=Tag(name=u'信阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'浉河区', u'平桥区', u'罗山县', u'光山县', u'新县', u'商城县', u'固始县', u'潢川县', u'淮滨县', u'息县']])
    key=key.parent()
    tag=Tag(name=u'南阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'宛城区', u'卧龙区', u'南召县', u'方城县', u'西峡县', u'镇平县', u'内乡县', u'淅川县', u'社旗县', u'唐河县', u'新野县', u'桐柏县', u'邓州市']])
    key=key.parent()
    tag=Tag(name=u'开封市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'龙亭区', u'顺河回族区', u'鼓楼区', u'禹王台区', u'金明区', u'杞县', u'通许县', u'尉氏县', u'开封县', u'兰考县']])
    key=key.parent()
    tag=Tag(name=u'洛阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'老城区', u'西工区', u'瀍河回族区', u'涧西区', u'吉利区', u'洛龙区', u'孟津县', u'新安县', u'栾川县', u'嵩县', u'汝阳县', u'宜阳县', u'洛宁县', u'伊川县', u'偃师市']])
    key=key.parent()
    tag=Tag(name=u'济源市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'焦作市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'解放区', u'中站区', u'马村区', u'山阳区', u'修武县', u'博爱县', u'武陟县', u'温县', u'沁阳市', u'孟州市']])
    key=key.parent()
    tag=Tag(name=u'鹤壁市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'鹤山区', u'山城区', u'淇滨区', u'浚县', u'淇县']])
    key=key.parent()
    tag=Tag(name=u'濮阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'华龙区', u'清丰县', u'南乐县', u'范县', u'台前县', u'濮阳县']])
    key=key.parent()
    tag=Tag(name=u'周口市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'川汇区', u'扶沟县', u'西华县', u'商水县', u'沈丘县', u'郸城县', u'淮阳县', u'太康县', u'鹿邑县', u'项城市']])
    key=key.parent()
    tag=Tag(name=u'漯河市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'源汇区', u'郾城区', u'召陵区', u'舞阳县', u'临颍县']])
    key=key.parent()
    tag=Tag(name=u'驻马店市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'驿城区', u'西平县', u'上蔡县', u'平舆县', u'正阳县', u'确山县', u'泌阳县', u'汝南县', u'遂平县', u'新蔡县']])
    key=key.parent()
    tag=Tag(name=u'三门峡市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'湖滨区', u'渑池县', u'陕县', u'卢氏县', u'义马市', u'灵宝市']])
    key=key.parent()
    tag=Tag(name=u'湖北省', depth=1)
    key=tag.put()
    tag=Tag(name=u'武汉市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'江岸区', u'江汉区', u'硚口区', u'汉阳区', u'武昌区', u'青山区', u'洪山区', u'东西湖区', u'汉南区', u'蔡甸区', u'江夏区', u'黄陂区', u'新洲区']])
    key=key.parent()
    tag=Tag(name=u'襄樊市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'襄城区', u'樊城区', u'襄阳区', u'南漳县', u'谷城县', u'保康县', u'老河口市', u'枣阳市', u'宜城市']])
    key=key.parent()
    tag=Tag(name=u'鄂州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'梁子湖区', u'华容区', u'鄂城区']])
    key=key.parent()
    tag=Tag(name=u'孝感市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'孝南区', u'孝昌县', u'大悟县', u'云梦县', u'应城市', u'安陆市', u'汉川市']])
    key=key.parent()
    tag=Tag(name=u'黄冈市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'黄州区', u'团风县', u'红安县', u'罗田县', u'英山县', u'浠水县', u'蕲春县', u'黄梅县', u'麻城市', u'武穴市']])
    key=key.parent()
    tag=Tag(name=u'黄石市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'黄石港区', u'西塞山区', u'下陆区', u'铁山区', u'阳新县', u'大冶市']])
    key=key.parent()
    tag=Tag(name=u'咸宁市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'咸安区', u'嘉鱼县', u'通城县', u'崇阳县', u'通山县', u'赤壁市']])
    key=key.parent()
    tag=Tag(name=u'荆州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'沙市区', u'荆州区', u'公安县', u'监利县', u'江陵县', u'石首市', u'洪湖市', u'松滋市']])
    key=key.parent()
    tag=Tag(name=u'宜昌市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'西陵区', u'伍家岗区', u'点军区', u'猇亭区', u'夷陵区', u'远安县', u'兴山县', u'秭归县', u'长阳土家族自治县', u'五峰土家族自治县', u'宜都市', u'当阳市', u'枝江市']])
    key=key.parent()
    tag=Tag(name=u'恩施土家族苗族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'恩施市', u'利川市', u'建始县', u'巴东县', u'宣恩县', u'咸丰县', u'来凤县', u'鹤峰县']])
    key=key.parent()
    tag=Tag(name=u'神农架林区', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'十堰市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'茅箭区', u'张湾区', u'郧县', u'郧西县', u'竹山县', u'竹溪县', u'房县', u'丹江口市']])
    key=key.parent()
    tag=Tag(name=u'随州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'曾都区', u'广水市']])
    key=key.parent()
    tag=Tag(name=u'荆门市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'东宝区', u'掇刀区', u'京山县', u'沙洋县', u'钟祥市']])
    key=key.parent()
    tag=Tag(name=u'仙桃市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'天门市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'潜江市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'湖南省', depth=1)
    key=tag.put()
    tag=Tag(name=u'岳阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'岳阳楼区', u'云溪区', u'君山区', u'岳阳县', u'华容县', u'湘阴县', u'平江县', u'汨罗市', u'临湘市']])
    key=key.parent()
    tag=Tag(name=u'长沙市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'芙蓉区', u'天心区', u'岳麓区', u'开福区', u'雨花区', u'长沙县', u'望城县', u'宁乡县', u'浏阳市']])
    key=key.parent()
    tag=Tag(name=u'湘潭市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'雨湖区', u'岳塘区', u'湘潭县', u'湘乡市', u'韶山市']])
    key=key.parent()
    tag=Tag(name=u'株洲市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'荷塘区', u'芦淞区', u'石峰区', u'天元区', u'株洲县', u'攸县', u'茶陵县', u'炎陵县', u'醴陵市']])
    key=key.parent()
    tag=Tag(name=u'衡阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'珠晖区', u'雁峰区', u'石鼓区', u'蒸湘区', u'南岳区', u'衡阳县', u'衡南县', u'衡山县', u'衡东县', u'祁东县', u'耒阳市', u'常宁市']])
    key=key.parent()
    tag=Tag(name=u'郴州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'北湖区', u'苏仙区', u'桂阳县', u'宜章县', u'永兴县', u'嘉禾县', u'临武县', u'汝城县', u'桂东县', u'安仁县', u'资兴市']])
    key=key.parent()
    tag=Tag(name=u'常德市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'武陵区', u'鼎城区', u'安乡县', u'汉寿县', u'澧县', u'临澧县', u'桃源县', u'石门县', u'津市市']])
    key=key.parent()
    tag=Tag(name=u'益阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'资阳区', u'赫山区', u'南县', u'桃江县', u'安化县', u'沅江市']])
    key=key.parent()
    tag=Tag(name=u'娄底市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'娄星区', u'双峰县', u'新化县', u'冷水江市', u'涟源市']])
    key=key.parent()
    tag=Tag(name=u'邵阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'双清区', u'大祥区', u'北塔区', u'邵东县', u'新邵县', u'邵阳县', u'隆回县', u'洞口县', u'绥宁县', u'新宁县', u'城步苗族自治县', u'武冈市']])
    key=key.parent()
    tag=Tag(name=u'湘西土家族苗族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'吉首市', u'泸溪县', u'凤凰县', u'花垣县', u'保靖县', u'古丈县', u'永顺县', u'龙山县']])
    key=key.parent()
    tag=Tag(name=u'张家界市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'永定区', u'武陵源区', u'慈利县', u'桑植县']])
    key=key.parent()
    tag=Tag(name=u'怀化市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'鹤城区', u'中方县', u'沅陵县', u'辰溪县', u'溆浦县', u'会同县', u'麻阳苗族自治县', u'新晃侗族自治县', u'芷江侗族自治县', u'靖州苗族侗族自治县', u'通道侗族自治县', u'洪江市']])
    key=key.parent()
    tag=Tag(name=u'永州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'零陵区', u'冷水滩区', u'祁阳县', u'东安县', u'双牌县', u'道县', u'江永县', u'宁远县', u'蓝山县', u'新田县', u'江华瑶族自治县']])
    key=key.parent()
    tag=Tag(name=u'广东省', depth=1)
    key=tag.put()
    tag=Tag(name=u'广州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'从化市', u'荔湾区', u'越秀区', u'海珠区', u'天河区', u'白云区', u'花都区', u'黄埔区', u'萝岗区', u'南沙区', u'番禺区', u'增城市']])
    key=key.parent()
    tag=Tag(name=u'汕尾市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'海丰县', u'陆河县', u'陆丰市']])
    key=key.parent()
    tag=Tag(name=u'阳江市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'江城区', u'阳西县', u'阳东县', u'阳春市']])
    key=key.parent()
    tag=Tag(name=u'揭阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'榕城区', u'揭东县', u'揭西县', u'惠来县', u'普宁市']])
    key=key.parent()
    tag=Tag(name=u'茂名市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'茂南区', u'茂港区', u'电白县', u'高州市', u'化州市', u'信宜市']])
    key=key.parent()
    tag=Tag(name=u'惠州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'惠城区', u'惠阳区', u'博罗县', u'惠东县', u'龙门县']])
    key=key.parent()
    tag=Tag(name=u'江门市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'蓬江区', u'江海区', u'新会区', u'台山市', u'开平市', u'鹤山市', u'恩平市']])
    key=key.parent()
    tag=Tag(name=u'韶关市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'武江区', u'浈江区', u'曲江区', u'始兴县', u'仁化县', u'翁源县', u'乳源瑶族自治县', u'新丰县', u'乐昌市', u'南雄市']])
    key=key.parent()
    tag=Tag(name=u'梅州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'梅江区', u'梅县', u'大埔县', u'丰顺县', u'五华县', u'平远县', u'蕉岭县', u'兴宁市']])
    key=key.parent()
    tag=Tag(name=u'汕头市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'龙湖区', u'金平区', u'濠江区', u'潮阳区', u'潮南区', u'澄海区', u'南澳县']])
    key=key.parent()
    tag=Tag(name=u'深圳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'罗湖区', u'福田区', u'南山区', u'宝安区', u'龙岗区', u'盐田区']])
    key=key.parent()
    tag=Tag(name=u'珠海市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'香洲区', u'斗门区', u'金湾区']])
    key=key.parent()
    tag=Tag(name=u'佛山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'禅城区', u'南海区', u'顺德区', u'三水区', u'高明区']])
    key=key.parent()
    tag=Tag(name=u'肇庆市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'端州区', u'鼎湖区', u'广宁县', u'怀集县', u'封开县', u'德庆县', u'高要市', u'四会市']])
    key=key.parent()
    tag=Tag(name=u'湛江市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'赤坎区', u'霞山区', u'坡头区', u'麻章区', u'遂溪县', u'徐闻县', u'廉江市', u'雷州市', u'吴川市']])
    key=key.parent()
    tag=Tag(name=u'中山市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'河源市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'源城区', u'紫金县', u'龙川县', u'连平县', u'和平县', u'东源县']])
    key=key.parent()
    tag=Tag(name=u'清远市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'清城区', u'佛冈县', u'阳山县', u'连山壮族瑶族自治县', u'连南瑶族自治县', u'清新县', u'英德市', u'连州市']])
    key=key.parent()
    tag=Tag(name=u'云浮市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'云城区', u'新兴县', u'郁南县', u'云安县', u'罗定市']])
    key=key.parent()
    tag=Tag(name=u'潮州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'湘桥区', u'潮安县', u'饶平县']])
    key=key.parent()
    tag=Tag(name=u'东莞市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'甘肃省', depth=1)
    key=tag.put()
    tag=Tag(name=u'兰州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'城关区', u'七里河区', u'西固区', u'安宁区', u'红古区', u'永登县', u'皋兰县', u'榆中县']])
    key=key.parent()
    tag=Tag(name=u'金昌市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'金川区', u'永昌县']])
    key=key.parent()
    tag=Tag(name=u'白银市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'白银区', u'平川区', u'靖远县', u'会宁县', u'景泰县']])
    key=key.parent()
    tag=Tag(name=u'天水市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'秦州区', u'麦积区', u'清水县', u'秦安县', u'甘谷县', u'武山县', u'张家川回族自治县']])
    key=key.parent()
    tag=Tag(name=u'嘉峪关市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'武威市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'凉州区', u'民勤县', u'古浪县', u'天祝藏族自治县']])
    key=key.parent()
    tag=Tag(name=u'张掖市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'甘州区', u'肃南裕固族自治县', u'民乐县', u'临泽县', u'高台县', u'山丹县']])
    key=key.parent()
    tag=Tag(name=u'平凉市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'崆峒区', u'泾川县', u'灵台县', u'崇信县', u'华亭县', u'庄浪县', u'静宁县']])
    key=key.parent()
    tag=Tag(name=u'酒泉市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'肃州区', u'金塔县', u'瓜州县', u'肃北蒙古族自治县', u'阿克塞哈萨克族自治县', u'玉门市', u'敦煌市']])
    key=key.parent()
    tag=Tag(name=u'庆阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'西峰区', u'庆城县', u'环县', u'华池县', u'合水县', u'正宁县', u'宁县', u'镇原县']])
    key=key.parent()
    tag=Tag(name=u'定西市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'安定区', u'通渭县', u'陇西县', u'渭源县', u'临洮县', u'漳县', u'岷县']])
    key=key.parent()
    tag=Tag(name=u'陇南市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'武都区', u'成县', u'文县', u'宕昌县', u'康县', u'西和县', u'礼县', u'徽县', u'两当县']])
    key=key.parent()
    tag=Tag(name=u'临夏回族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'临夏市', u'临夏县', u'康乐县', u'永靖县', u'广河县', u'和政县', u'东乡族自治县', u'积石山保安族东乡族撒拉族自治县']])
    key=key.parent()
    tag=Tag(name=u'甘南藏族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'合作市', u'临潭县', u'卓尼县', u'舟曲县', u'迭部县', u'玛曲县', u'碌曲县', u'夏河县']])
    key=key.parent()
    tag=Tag(name=u'四川省', depth=1)
    key=tag.put()
    tag=Tag(name=u'成都市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'锦江区', u'青羊区', u'金牛区', u'武侯区', u'成华区', u'龙泉驿区', u'青白江区', u'新都区', u'温江区', u'金堂县', u'双流县', u'郫县', u'大邑县', u'蒲江县', u'新津县', u'都江堰市', u'彭州市', u'邛崃市', u'崇州市']])
    key=key.parent()
    tag=Tag(name=u'攀枝花市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'东区', u'西区', u'仁和区', u'米易县', u'盐边县']])
    key=key.parent()
    tag=Tag(name=u'自贡市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'自流井区', u'贡井区', u'大安区', u'沿滩区', u'荣县', u'富顺县']])
    key=key.parent()
    tag=Tag(name=u'绵阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'涪城区', u'游仙区', u'三台县', u'盐亭县', u'安县', u'梓潼县', u'北川羌族自治县', u'平武县', u'江油市']])
    key=key.parent()
    tag=Tag(name=u'南充市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'顺庆区', u'高坪区', u'嘉陵区', u'南部县', u'营山县', u'蓬安县', u'仪陇县', u'西充县', u'阆中市']])
    key=key.parent()
    tag=Tag(name=u'达州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'通川区', u'达县', u'宣汉县', u'开江县', u'大竹县', u'渠县', u'万源市']])
    key=key.parent()
    tag=Tag(name=u'遂宁市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'船山区', u'安居区', u'蓬溪县', u'射洪县', u'大英县']])
    key=key.parent()
    tag=Tag(name=u'广安市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'广安区', u'岳池县', u'武胜县', u'邻水县', u'华蓥市']])
    key=key.parent()
    tag=Tag(name=u'巴中市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'巴州区', u'通江县', u'南江县', u'平昌县']])
    key=key.parent()
    tag=Tag(name=u'泸州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'江阳区', u'纳溪区', u'龙马潭区', u'泸县', u'合江县', u'叙永县', u'古蔺县']])
    key=key.parent()
    tag=Tag(name=u'宜宾市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'翠屏区', u'宜宾县', u'南溪县', u'江安县', u'长宁县', u'高县', u'珙县', u'筠连县', u'兴文县', u'屏山县']])
    key=key.parent()
    tag=Tag(name=u'资阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'雁江区', u'安岳县', u'乐至县', u'简阳市']])
    key=key.parent()
    tag=Tag(name=u'内江市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'市中区', u'东兴区', u'威远县', u'资中县', u'隆昌县']])
    key=key.parent()
    tag=Tag(name=u'乐山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'市中区', u'沙湾区', u'五通桥区', u'金口河区', u'犍为县', u'井研县', u'夹江县', u'沐川县', u'峨边彝族自治县', u'马边彝族自治县', u'峨眉山市']])
    key=key.parent()
    tag=Tag(name=u'眉山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'东坡区', u'仁寿县', u'彭山县', u'洪雅县', u'丹棱县', u'青神县']])
    key=key.parent()
    tag=Tag(name=u'凉山彝族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'西昌市', u'木里藏族自治县', u'盐源县', u'德昌县', u'会理县', u'会东县', u'宁南县', u'普格县', u'布拖县', u'金阳县', u'昭觉县', u'喜德县', u'冕宁县', u'越西县', u'甘洛县', u'美姑县', u'雷波县']])
    key=key.parent()
    tag=Tag(name=u'雅安市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'雨城区', u'名山县', u'荥经县', u'汉源县', u'石棉县', u'天全县', u'芦山县', u'宝兴县']])
    key=key.parent()
    tag=Tag(name=u'甘孜藏族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'康定县', u'泸定县', u'丹巴县', u'九龙县', u'雅江县', u'道孚县', u'炉霍县', u'甘孜县', u'新龙县', u'德格县', u'白玉县', u'石渠县', u'色达县', u'理塘县', u'巴塘县', u'乡城县', u'稻城县', u'得荣县']])
    key=key.parent()
    tag=Tag(name=u'阿坝藏族羌族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'汶川县', u'理县', u'茂县', u'松潘县', u'九寨沟县', u'金川县', u'小金县', u'黑水县', u'马尔康县', u'壤塘县', u'阿坝县', u'若尔盖县', u'红原县']])
    key=key.parent()
    tag=Tag(name=u'德阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'旌阳区', u'中江县', u'罗江县', u'广汉市', u'什邡市', u'绵竹市']])
    key=key.parent()
    tag=Tag(name=u'广元市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'市中区', u'元坝区', u'朝天区', u'旺苍县', u'青川县', u'剑阁县', u'苍溪县']])
    key=key.parent()
    tag=Tag(name=u'贵州省', depth=1)
    key=tag.put()
    tag=Tag(name=u'贵阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'南明区', u'云岩区', u'花溪区', u'乌当区', u'白云区', u'小河区', u'开阳县', u'息烽县', u'修文县', u'清镇市']])
    key=key.parent()
    tag=Tag(name=u'遵义市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'红花岗区', u'汇川区', u'遵义县', u'桐梓县', u'绥阳县', u'正安县', u'道真仡佬族苗族自治县', u'务川仡佬族苗族自治县', u'凤冈县', u'湄潭县', u'余庆县', u'习水县', u'赤水市', u'仁怀市']])
    key=key.parent()
    tag=Tag(name=u'安顺市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'西秀区', u'平坝县', u'普定县', u'镇宁布依族苗族自治县', u'关岭布依族苗族自治县', u'紫云苗族布依族自治县']])
    key=key.parent()
    tag=Tag(name=u'黔南布依族苗族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'都匀市', u'福泉市', u'荔波县', u'贵定县', u'瓮安县', u'独山县', u'平塘县', u'罗甸县', u'长顺县', u'龙里县', u'惠水县', u'三都水族自治县']])
    key=key.parent()
    tag=Tag(name=u'黔东南苗族侗族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'凯里市', u'黄平县', u'施秉县', u'三穗县', u'镇远县', u'岑巩县', u'天柱县', u'锦屏县', u'剑河县', u'台江县', u'黎平县', u'榕江县', u'从江县', u'雷山县', u'麻江县', u'丹寨县']])
    key=key.parent()
    tag=Tag(name=u'铜仁地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'铜仁市', u'江口县', u'玉屏侗族自治县', u'石阡县', u'思南县', u'印江土家族苗族自治县', u'德江县', u'沿河土家族自治县', u'松桃苗族自治县', u'万山特区']])
    key=key.parent()
    tag=Tag(name=u'毕节地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'毕节市', u'大方县', u'黔西县', u'金沙县', u'织金县', u'纳雍县', u'威宁彝族回族苗族自治县', u'赫章县']])
    key=key.parent()
    tag=Tag(name=u'六盘水市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'钟山区', u'六枝特区', u'水城县', u'盘县']])
    key=key.parent()
    tag=Tag(name=u'黔西南布依族苗族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'兴义市', u'兴仁县', u'普安县', u'晴隆县', u'贞丰县', u'望谟县', u'册亨县', u'安龙县']])
    key=key.parent()
    tag=Tag(name=u'海南省', depth=1)
    key=tag.put()
    tag=Tag(name=u'海口市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'秀英区', u'龙华区', u'琼山区', u'美兰区']])
    key=key.parent()
    tag=Tag(name=u'三亚市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'五指山市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'琼海市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'儋州市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'文昌市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'万宁市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'东方市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'澄迈县', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'定安县', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'屯昌县', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'临高县', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'白沙黎族自治县', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'昌江黎族自治县', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'乐东黎族自治县', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'陵水黎族自治县', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'保亭黎族苗族自治县', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'琼中黎族苗族自治县', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'云南省', depth=1)
    key=tag.put()
    tag=Tag(name=u'西双版纳傣族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'景洪市', u'勐海县', u'勐腊县']])
    key=key.parent()
    tag=Tag(name=u'德宏傣族景颇族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'瑞丽市', u'潞西市', u'梁河县', u'盈江县', u'陇川县']])
    key=key.parent()
    tag=Tag(name=u'昭通市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'昭阳区', u'鲁甸县', u'巧家县', u'盐津县', u'大关县', u'永善县', u'绥江县', u'镇雄县', u'彝良县', u'威信县', u'水富县']])
    key=key.parent()
    tag=Tag(name=u'昆明市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'五华区', u'盘龙区', u'官渡区', u'西山区', u'东川区', u'呈贡县', u'晋宁县', u'富民县', u'宜良县', u'石林彝族自治县', u'嵩明县', u'禄劝彝族苗族自治县', u'寻甸回族彝族自治县', u'安宁市']])
    key=key.parent()
    tag=Tag(name=u'大理白族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'大理市', u'漾濞彝族自治县', u'祥云县', u'宾川县', u'弥渡县', u'南涧彝族自治县', u'巍山彝族回族自治县', u'永平县', u'云龙县', u'洱源县', u'剑川县', u'鹤庆县']])
    key=key.parent()
    tag=Tag(name=u'红河哈尼族彝族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'个旧市', u'开远市', u'蒙自县', u'屏边苗族自治县', u'建水县', u'石屏县', u'弥勒县', u'泸西县', u'元阳县', u'红河县', u'金平苗族瑶族傣族自治县', u'绿春县', u'河口瑶族自治县']])
    key=key.parent()
    tag=Tag(name=u'曲靖市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'麒麟区', u'马龙县', u'陆良县', u'师宗县', u'罗平县', u'富源县', u'会泽县', u'沾益县', u'宣威市']])
    key=key.parent()
    tag=Tag(name=u'保山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'隆阳区', u'施甸县', u'腾冲县', u'龙陵县', u'昌宁县']])
    key=key.parent()
    tag=Tag(name=u'文山壮族苗族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'文山县', u'砚山县', u'西畴县', u'麻栗坡县', u'马关县', u'丘北县', u'广南县', u'富宁县']])
    key=key.parent()
    tag=Tag(name=u'玉溪市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'红塔区', u'江川县', u'澄江县', u'通海县', u'华宁县', u'易门县', u'峨山彝族自治县', u'新平彝族傣族自治县', u'元江哈尼族彝族傣族自治县']])
    key=key.parent()
    tag=Tag(name=u'楚雄彝族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'楚雄市', u'双柏县', u'牟定县', u'南华县', u'姚安县', u'大姚县', u'永仁县', u'元谋县', u'武定县', u'禄丰县']])
    key=key.parent()
    tag=Tag(name=u'普洱市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'思茅区', u'宁洱哈尼族彝族自治县', u'墨江哈尼族自治县', u'景东彝族自治县', u'景谷傣族彝族自治县', u'镇沅彝族哈尼族拉祜族自治县', u'江城哈尼族彝族自治县', u'孟连傣族拉祜族佤族自治县', u'澜沧拉祜族自治县', u'西盟佤族自治县']])
    key=key.parent()
    tag=Tag(name=u'临沧市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'临翔区', u'凤庆县', u'云县', u'永德县', u'镇康县', u'双江拉祜族佤族布朗族傣族自治县', u'耿马傣族佤族自治县', u'沧源佤族自治县']])
    key=key.parent()
    tag=Tag(name=u'怒江傈傈族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'泸水县', u'福贡县', u'贡山独龙族怒族自治县', u'兰坪白族普米族自治县']])
    key=key.parent()
    tag=Tag(name=u'迪庆藏族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'香格里拉县', u'德钦县', u'维西傈僳族自治县']])
    key=key.parent()
    tag=Tag(name=u'丽江市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'古城区', u'玉龙纳西族自治县', u'永胜县', u'华坪县', u'宁蒗彝族自治县']])
    key=key.parent()
    tag=Tag(name=u'青海省', depth=1)
    key=tag.put()
    tag=Tag(name=u'海北藏族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'门源回族自治县', u'祁连县', u'海晏县', u'刚察县']])
    key=key.parent()
    tag=Tag(name=u'西宁市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'城东区', u'城中区', u'城西区', u'城北区', u'大通回族土族自治县', u'湟中县', u'湟源县']])
    key=key.parent()
    tag=Tag(name=u'海东地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'平安县', u'民和回族土族自治县', u'乐都县', u'互助土族自治县', u'化隆回族自治县', u'循化撒拉族自治县']])
    key=key.parent()
    tag=Tag(name=u'黄南藏族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'同仁县', u'尖扎县', u'泽库县', u'河南蒙古族自治县']])
    key=key.parent()
    tag=Tag(name=u'海南藏族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'共和县', u'同德县', u'贵德县', u'兴海县', u'贵南县']])
    key=key.parent()
    tag=Tag(name=u'果洛藏族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'玛沁县', u'班玛县', u'甘德县', u'达日县', u'久治县', u'玛多县']])
    key=key.parent()
    tag=Tag(name=u'玉树藏族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'玉树县', u'杂多县', u'称多县', u'治多县', u'囊谦县', u'曲麻莱县']])
    key=key.parent()
    tag=Tag(name=u'海西蒙古族藏族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'格尔木市', u'德令哈市', u'乌兰县', u'都兰县', u'天峻县']])
    key=key.parent()
    tag=Tag(name=u'陕西省', depth=1)
    key=tag.put()
    tag=Tag(name=u'西安市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'新城区', u'碑林区', u'莲湖区', u'灞桥区', u'未央区', u'雁塔区', u'阎良区', u'临潼区', u'长安区', u'蓝田县', u'周至县', u'户县', u'高陵县']])
    key=key.parent()
    tag=Tag(name=u'咸阳市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'秦都区', u'杨陵区', u'渭城区', u'三原县', u'泾阳县', u'乾县', u'礼泉县', u'永寿县', u'彬县', u'长武县', u'旬邑县', u'淳化县', u'武功县', u'兴平市']])
    key=key.parent()
    tag=Tag(name=u'延安市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'宝塔区', u'延长县', u'延川县', u'子长县', u'安塞县', u'志丹县', u'吴起县', u'甘泉县', u'富县', u'洛川县', u'宜川县', u'黄龙县', u'黄陵县']])
    key=key.parent()
    tag=Tag(name=u'榆林市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'榆阳区', u'神木县', u'府谷县', u'横山县', u'靖边县', u'定边县', u'绥德县', u'米脂县', u'佳县', u'吴堡县', u'清涧县', u'子洲县']])
    key=key.parent()
    tag=Tag(name=u'渭南市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'临渭区', u'华县', u'潼关县', u'大荔县', u'合阳县', u'澄城县', u'蒲城县', u'白水县', u'富平县', u'韩城市', u'华阴市']])
    key=key.parent()
    tag=Tag(name=u'商洛市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'商州区', u'洛南县', u'丹凤县', u'商南县', u'山阳县', u'镇安县', u'柞水县']])
    key=key.parent()
    tag=Tag(name=u'安康市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'汉滨区', u'汉阴县', u'石泉县', u'宁陕县', u'紫阳县', u'岚皋县', u'平利县', u'镇坪县', u'旬阳县', u'白河县']])
    key=key.parent()
    tag=Tag(name=u'汉中市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'汉台区', u'南郑县', u'城固县', u'洋县', u'西乡县', u'勉县', u'宁强县', u'略阳县', u'镇巴县', u'留坝县', u'佛坪县']])
    key=key.parent()
    tag=Tag(name=u'宝鸡市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'渭滨区', u'金台区', u'陈仓区', u'凤翔县', u'岐山县', u'扶风县', u'眉县', u'陇县', u'千阳县', u'麟游县', u'凤县', u'太白县']])
    key=key.parent()
    tag=Tag(name=u'铜川市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'王益区', u'印台区', u'耀州区', u'宜君县']])
    key=key.parent()
    tag=Tag(name=u'广西壮族自治区', depth=1)
    key=tag.put()
    tag=Tag(name=u'防城港市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'港口区', u'防城区', u'上思县', u'东兴市']])
    key=key.parent()
    tag=Tag(name=u'南宁市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'兴宁区', u'青秀区', u'江南区', u'西乡塘区', u'良庆区', u'邕宁区', u'武鸣县', u'隆安县', u'马山县', u'上林县', u'宾阳县', u'横县']])
    key=key.parent()
    tag=Tag(name=u'崇左市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'江洲区', u'扶绥县', u'宁明县', u'龙州县', u'大新县', u'天等县', u'凭祥市']])
    key=key.parent()
    tag=Tag(name=u'来宾市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'兴宾区', u'忻城县', u'象州县', u'武宣县', u'金秀瑶族自治县', u'合山市']])
    key=key.parent()
    tag=Tag(name=u'柳州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'城中区', u'鱼峰区', u'柳南区', u'柳北区', u'柳江县', u'柳城县', u'鹿寨县', u'融安县', u'融水苗族自治县', u'三江侗族自治县']])
    key=key.parent()
    tag=Tag(name=u'桂林市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'秀峰区', u'叠彩区', u'象山区', u'七星区', u'雁山区', u'阳朔县', u'临桂县', u'灵川县', u'全州县', u'兴安县', u'永福县', u'灌阳县', u'龙胜各族自治县', u'资源县', u'平乐县', u'荔浦县', u'恭城瑶族自治县']])
    key=key.parent()
    tag=Tag(name=u'梧州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'万秀区', u'碟山区', u'长洲区', u'苍梧县', u'藤县', u'蒙山县', u'岑溪市']])
    key=key.parent()
    tag=Tag(name=u'贺州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'八步区', u'昭平县', u'钟山县', u'富川瑶族自治县']])
    key=key.parent()
    tag=Tag(name=u'贵港市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'港北区', u'港南区', u'覃塘区', u'平南县', u'桂平市']])
    key=key.parent()
    tag=Tag(name=u'玉林市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'玉州区', u'容县', u'陆川县', u'博白县', u'兴业县', u'北流市']])
    key=key.parent()
    tag=Tag(name=u'百色市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'右江区', u'田阳县', u'田东县', u'平果县', u'德保县', u'靖西县', u'那坡县', u'凌云县', u'乐业县', u'田林县', u'西林县', u'隆林各族自治县']])
    key=key.parent()
    tag=Tag(name=u'钦州市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'钦南区', u'钦北区', u'灵山县', u'浦北县']])
    key=key.parent()
    tag=Tag(name=u'河池市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'金城江区', u'南丹县', u'天峨县', u'凤山县', u'东兰县', u'罗城仫佬族自治县', u'环江毛南族自治县', u'巴马瑶族自治县', u'都安瑶族自治县', u'大化瑶族自治县', u'宜州市']])
    key=key.parent()
    tag=Tag(name=u'北海市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'海城区', u'银海区', u'铁山港区', u'合浦县']])
    key=key.parent()
    tag=Tag(name=u'西藏自治区', depth=1)
    key=tag.put()
    tag=Tag(name=u'拉萨市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'城关区', u'林周县', u'当雄县', u'尼木县', u'曲水县', u'堆龙德庆县', u'达孜县', u'墨竹工卡县']])
    key=key.parent()
    tag=Tag(name=u'日喀则地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'日喀则市', u'南木林县', u'江孜县', u'定日县', u'萨迦县', u'拉孜县', u'昂仁县', u'谢通门县', u'白朗县', u'仁布县', u'康马县', u'定结县', u'仲巴县', u'亚东县', u'吉隆县', u'聂拉木县', u'萨嘎县', u'岗巴县']])
    key=key.parent()
    tag=Tag(name=u'山南地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'乃东县', u'扎囊县', u'贡嘎县', u'桑日县', u'琼结县', u'曲松县', u'措美县', u'洛扎县', u'加查县', u'隆子县', u'错那县', u'浪卡子县']])
    key=key.parent()
    tag=Tag(name=u'林芝地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'林芝县', u'工布江达县', u'米林县', u'墨脱县', u'波密县', u'察隅县', u'朗县']])
    key=key.parent()
    tag=Tag(name=u'昌都地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'昌都县', u'江达县', u'贡觉县', u'类乌齐县', u'丁青县', u'察雅县', u'八宿县', u'左贡县', u'芒康县', u'洛隆县', u'边坝县']])
    key=key.parent()
    tag=Tag(name=u'那曲地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'那曲县', u'嘉黎县', u'比如县', u'聂荣县', u'安多县', u'申扎县', u'索县', u'班戈县', u'巴青县', u'尼玛县']])
    key=key.parent()
    tag=Tag(name=u'阿里地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'普兰县', u'札达县', u'噶尔县', u'日土县', u'革吉县', u'改则县', u'措勤县']])
    key=key.parent()
    tag=Tag(name=u'宁夏回族自治区', depth=1)
    key=tag.put()
    tag=Tag(name=u'银川市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'兴庆区', u'西夏区', u'金凤区', u'永宁县', u'贺兰县', u'灵武市']])
    key=key.parent()
    tag=Tag(name=u'石嘴山市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'大武口区', u'惠农区', u'平罗县']])
    key=key.parent()
    tag=Tag(name=u'吴忠市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'利通区', u'盐池县', u'同心县', u'青铜峡市']])
    key=key.parent()
    tag=Tag(name=u'固原市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'原州区', u'西吉县', u'隆德县', u'泾源县', u'彭阳县']])
    key=key.parent()
    tag=Tag(name=u'中卫市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'沙坡头区', u'中宁县', u'海原县']])
    key=key.parent()
    tag=Tag(name=u'新疆维吾尔自治区', depth=1)
    key=tag.put()
    tag=Tag(name=u'塔城地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'塔城市', u'乌苏市', u'额敏县', u'沙湾县', u'托里县', u'裕民县', u'和布克赛尔蒙古自治县']])
    key=key.parent()
    tag=Tag(name=u'哈密地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'哈密市', u'巴里坤哈萨克自治县', u'伊吾县']])
    key=key.parent()
    tag=Tag(name=u'和田地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'和田市', u'和田县', u'墨玉县', u'皮山县', u'洛浦县', u'策勒县', u'于田县', u'民丰县']])
    key=key.parent()
    tag=Tag(name=u'阿勒泰地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'阿勒泰市', u'布尔津县', u'富蕴县', u'福海县', u'哈巴河县', u'青河县', u'吉木乃县']])
    key=key.parent()
    tag=Tag(name=u'克孜勒苏柯尔克孜自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'阿图什市', u'阿克陶县', u'阿合奇县', u'乌恰县']])
    key=key.parent()
    tag=Tag(name=u'博尔塔拉蒙古自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'博乐市', u'精河县', u'温泉县']])
    key=key.parent()
    tag=Tag(name=u'克拉玛依市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'独山子区', u'克拉玛依区', u'白碱滩区', u'乌尔禾区']])
    key=key.parent()
    tag=Tag(name=u'乌鲁木齐市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'天山区', u'沙依巴克区', u'新市区', u'水磨沟区', u'头屯河区', u'达坂城区', u'米东区', u'乌鲁木齐县']])
    key=key.parent()
    tag=Tag(name=u'石河子市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'昌吉回族自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'昌吉市', u'阜康市', u'呼图壁县', u'玛纳斯县', u'奇台县', u'吉木萨尔县', u'木垒哈萨克自治县']])
    key=key.parent()
    tag=Tag(name=u'五家渠市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'吐鲁番地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'吐鲁番市', u'鄯善县', u'托克逊县']])
    key=key.parent()
    tag=Tag(name=u'巴音郭楞蒙古自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'库尔勒市', u'轮台县', u'尉犁县', u'若羌县', u'且末县', u'焉耆回族自治县', u'和静县', u'和硕县', u'博湖县']])
    key=key.parent()
    tag=Tag(name=u'阿克苏地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'阿克苏市', u'温宿县', u'库车县', u'沙雅县', u'新和县', u'拜城县', u'乌什县', u'阿瓦提县', u'柯坪县']])
    key=key.parent()
    tag=Tag(name=u'阿拉尔市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'喀什地区', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'喀什市', u'疏附县', u'疏勒县', u'英吉沙县', u'泽普县', u'莎车县', u'叶城县', u'麦盖提县', u'岳普湖县', u'伽师县', u'巴楚县', u'塔什库尔干塔吉克自治县']])
    key=key.parent()
    tag=Tag(name=u'图木舒克市', parent=key, depth=2)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'伊犁哈萨克自治州', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'伊宁市', u'奎屯市', u'伊宁县', u'察布查尔锡伯自治县', u'霍城县', u'巩留县', u'新源县', u'昭苏县', u'特克斯县', u'尼勒克县']])
    key=key.parent()
    tag=Tag(name=u'内蒙古自治区', depth=1)
    key=tag.put()
    tag=Tag(name=u'呼伦贝尔市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'海拉尔区', u'阿荣旗', u'莫力达瓦达斡尔族自治旗', u'鄂伦春自治旗', u'鄂温克族自治旗', u'陈巴尔虎旗', u'新巴尔虎左旗', u'新巴尔虎右旗', u'满洲里市', u'牙克石市', u'扎兰屯市', u'额尔古纳市', u'根河市']])
    key=key.parent()
    tag=Tag(name=u'呼和浩特市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'新城区', u'回民区', u'玉泉区', u'赛罕区', u'土默特左旗', u'托克托县', u'和林格尔县', u'清水河县', u'武川县']])
    key=key.parent()
    tag=Tag(name=u'包头市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'东河区', u'昆都仑区', u'青山区', u'石拐区', u'白云鄂博矿区', u'九原区', u'土默特右旗', u'固阳县', u'达尔罕茂明安联合旗']])
    key=key.parent()
    tag=Tag(name=u'乌海市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'海勃湾区', u'海南区', u'乌达区']])
    key=key.parent()
    tag=Tag(name=u'乌兰察布市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'集宁区', u'卓资县', u'化德县', u'商都县', u'兴和县', u'凉城县', u'察哈尔右翼前旗', u'察哈尔右翼中旗', u'察哈尔右翼后旗', u'四子王旗', u'丰镇市']])
    key=key.parent()
    tag=Tag(name=u'通辽市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'科尔沁区', u'科尔沁左翼中旗', u'科尔沁左翼后旗', u'开鲁县', u'库伦旗', u'奈曼旗', u'扎鲁特旗', u'霍林郭勒市']])
    key=key.parent()
    tag=Tag(name=u'赤峰市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'红山区', u'元宝山区', u'松山区', u'阿鲁科尔沁旗', u'巴林左旗', u'巴林右旗', u'林西县', u'克什克腾旗', u'翁牛特旗', u'喀喇沁旗', u'宁城县', u'敖汉旗']])
    key=key.parent()
    tag=Tag(name=u'鄂尔多斯市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'东胜区', u'达拉特旗', u'准格尔旗', u'鄂托克前旗', u'鄂托克旗', u'杭锦旗', u'乌审旗', u'伊金霍洛旗']])
    key=key.parent()
    tag=Tag(name=u'巴彦淖尔市', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'临河区', u'五原县', u'磴口县', u'乌拉特前旗', u'乌拉特中旗', u'乌拉特后旗', u'杭锦后旗']])
    key=key.parent()
    tag=Tag(name=u'锡林郭勒盟', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'二连浩特市', u'锡林浩特市', u'阿巴嘎旗', u'苏尼特左旗', u'苏尼特右旗', u'东乌珠穆沁旗', u'西乌珠穆沁旗', u'太仆寺旗', u'镶黄旗', u'正镶白旗', u'正蓝旗', u'多伦县']])
    key=key.parent()
    tag=Tag(name=u'兴安盟', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'乌兰浩特市', u'阿尔山市', u'科尔沁右翼前旗', u'科尔沁右翼中旗', u'扎赉特旗', u'突泉县']])
    key=key.parent()
    tag=Tag(name=u'阿拉善盟', parent=key, depth=2)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=3) for t in [u'阿拉善左旗', u'阿拉善右旗', u'额济纳旗']])
    key=key.parent()
    tag=Tag(name=u'澳门特别行政区', depth=1)
    key=tag.put()
    key=key.parent()
    tag=Tag(name=u'香港特别行政区', depth=1)
    key=tag.put()
    key=key.parent()

def forum(request):
    deferred.defer(populate_forum)
    return  render_to_response('tasteofhome/index.html', {'message': 'deferred forum population'})

def populate_forum():
    tag=Tag(name=u'论坛', depth=99)
    key=tag.put()
    db.put([Tag(parent=key, name=t, depth=100) for t in [u'公告', u'提问', u'反馈', u'开发者']])

def create_admin():
    from yan.auth import create_new_user
    create_new_user('motor@samdeha.com', 'motor', 'omerta', is_admin=True)
